// TODO: Create a function that returns a license badge based on which license is passed in
// If there is no license, return an empty string

function renderLicenseBadge(license = "") { 
  if (!license || license!=='MIT' || license!=='Apache' || license!=='GPL') {
    return '___NONE___'
  } 

  return `![license badge](https://img.shields.io/badge/license-${license}-orange)`
}

// TODO: Create a function that returns the license link
// If there is no license, return an empty string
function renderLicenseLink(license) { 
  if (!license || license!=='MIT' || license!=='Apache' || license!=='GPL') {
    return '___NONE___'
  }

  return `[license badge](https://opensource.org/licenses/${license}-orange)`
}

// TODO: Create a function that returns the license section of README
// If there is no license, return an empty string
function renderLicenseSection(license) { }


// function to generate markdown for README
function generateMarkdown(data) {
  return `
<h1 align="center">${data.title}</h1>
  
![badge](https://img.shields.io/badge/license-${data.license}-orange)<br />
## Description
   ${data.description}
## Table of Contents
- [Description](#description)
- [Installation](#installation)
- [Usage](#usage)
- [License](#license)
- [Contributing](#contributing)
- [Tests](#tests)
- [Questions](#questions)
## Installation
   ${data.installation}
## Usage
   ${data.usage}
## License
![license badge](https://img.shields.io/badge/license-${license}-orange)
    ${renderLicenseBadge(data.license)};
    ${renderLicenseLink(data.license)};
    ${renderLicenseSection(data.license)};
<br />
This application is legally covered by the ${data.license} license. 
<br />
## Contributing
   ${data.contributing}
## Tests
   ${data.tests}
## Questions
   ${data.questions}<br />
<br />
   You can find me on GitHub: [${data.username}](https://github.com/${data.username})<br />
<br />
   You can reach me with additional questions on: ${data.email}<br /><br />
   This README was generated by [README-generator](https://github.com/ivanduranic/readme-generator)
    `;
}

module.exports = generateMarkdown;